version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

  migrations:
    image: migrations:latest
    container_name: migrations
    environment:
      DB_ENDPOINT: 'http://dynamodb-local:8000'
    command: >
      /bin/sh -c 'export MIGRATION_SEEDER=initial-table && node main && sleep 5s && export MIGRATION_SEEDER=initial-data && node main'
    depends_on:
      - dynamodb-local

  api:
    image: api:latest
    container_name: api
    ports:
      - '9000:8080'
    environment:
      DB_ENDPOINT: 'http://dynamodb-local:8000'
    depends_on:
      - migrations
  
  web-app:
    image: web.app:latest
    container_name: web.app
    ports:
      - '5000:80'
    environment:
      PRACTERA_GQL_URL: 'http://api:9000/graphql'
      PRACTERA_VERSION: 'v8.8.5'
    depends_on:
      - api
