apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30110
      protocol: TCP
  type: NodePort
  selector:
    app: api
