apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  labels:
    app: dynamodb-local
spec:
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30120
      protocol: TCP
  type: NodePort
  selector:
    app: dynamodb-local
