apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  ports:
    - port: 4000
      targetPort: 80
      nodePort: 30100
      protocol: TCP
  type: NodePort
  selector:
    app: web-app
