kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: practera-badge
nodes:
  - role: control-plane
    extraPortMappings:
      # app
      - containerPort: 30100
        hostPort: 4000
        protocol: TCP
      # api
      - containerPort: 30110
        hostPort: 5000
        protocol: TCP
      # dynamodb local
      - containerPort: 30120
        hostPort: 8000
        protocol: TCP
      # dynamodb admin
      - containerPort: 30130
        hostPort: 9000
        protocol: TCP