---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  ENVIRONMENT: dev
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: local
  AWS_SECRET_ACCESS_KEY: local
  DB_ENDPOINT: 'http://dynamodb-local:8000'
  DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'