apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: migrations
          image: migrations:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: common-config
          env:
            - name: ENTRY_POINT
              value: seeds
            - name: MIGRATION_SEEDER
              value: initial-table
            - name: DB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_ENDPOINT
      restartPolicy: Never
